--------------------------------------------------------
--  File created - œroda-kwietnia-19-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UCZNIOWIE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UCZNIOWIE" 
   (	"ID_UCZNIA" NUMBER, 
	"IMIE" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(20 BYTE), 
	"DATA_URODZENIA" DATE, 
	"MIASTO" VARCHAR2(20 BYTE), 
	"ULICA" VARCHAR2(20 BYTE), 
	"KOD_POCZTOWY" VARCHAR2(6 BYTE), 
	"IMIE_MATKI" VARCHAR2(20 BYTE), 
	"TELEFON_MATKI" VARCHAR2(9 BYTE), 
	"IMIE_OJCA" VARCHAR2(20 BYTE), 
	"TELEFON_OJCA" VARCHAR2(9 BYTE), 
	"ID_GRUPY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STANOWISKA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STANOWISKA" 
   (	"ID_STANOWISKA" NUMBER, 
	"NAZWA" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRZEDMIOTY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PRZEDMIOTY" 
   (	"ID_PRZEDMIOTU" NUMBER, 
	"NAZWA_PRZEDMIOTU" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NAUCZYCIELE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."NAUCZYCIELE" 
   (	"ID_NAUCZYCIELA" NUMBER, 
	"IMIE" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(20 BYTE), 
	"ID_STANOWISKA" NUMBER, 
	"ID_PRZEDMIOTU" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LISTA_OBCENOSCI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LISTA_OBCENOSCI" 
   (	"ID_REKORDU" NUMBER, 
	"DATA" DATE, 
	"CZY_BYL" NUMBER(1,0), 
	"ID_PRZEDMIOTU" NUMBER, 
	"ID_UCZNIA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRUPY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GRUPY" 
   (	"ID_GRUPY" NUMBER, 
	"DATA_ZALOZENIA" DATE, 
	"NAZWA_GRUPY" VARCHAR2(3 BYTE), 
	"ID_PRACOWNIKA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.UCZNIOWIE
SET DEFINE OFF;
Insert into SYSTEM.UCZNIOWIE (ID_UCZNIA,IMIE,NAZWISKO,DATA_URODZENIA,MIASTO,ULICA,KOD_POCZTOWY,IMIE_MATKI,TELEFON_MATKI,IMIE_OJCA,TELEFON_OJCA,ID_GRUPY) values ('1','Lechos³awa','Adamska',to_date('13/12/30','RR/MM/DD'),'Wroc³aw','Nyska 138','50-504','Julia','722578938','Tomasz','795685550','1');
Insert into SYSTEM.UCZNIOWIE (ID_UCZNIA,IMIE,NAZWISKO,DATA_URODZENIA,MIASTO,ULICA,KOD_POCZTOWY,IMIE_MATKI,TELEFON_MATKI,IMIE_OJCA,TELEFON_OJCA,ID_GRUPY) values ('2','Felicja','Kamiñska',to_date('13/04/20','RR/MM/DD'),'Kielce','Lecha 98','25-622','Karolina','666229104','Stefan','799220109','1');
Insert into SYSTEM.UCZNIOWIE (ID_UCZNIA,IMIE,NAZWISKO,DATA_URODZENIA,MIASTO,ULICA,KOD_POCZTOWY,IMIE_MATKI,TELEFON_MATKI,IMIE_OJCA,TELEFON_OJCA,ID_GRUPY) values ('3','Marian','Ostrowski',to_date('13/07/18','RR/MM/DD'),'Kielce','Stwosza Wita 11','25-622','Barbara','690332815','Piotr','888536315','2');
REM INSERTING into SYSTEM.STANOWISKA
SET DEFINE OFF;
Insert into SYSTEM.STANOWISKA (ID_STANOWISKA,NAZWA) values ('1','Pedagog');
Insert into SYSTEM.STANOWISKA (ID_STANOWISKA,NAZWA) values ('2','Logopeda');
Insert into SYSTEM.STANOWISKA (ID_STANOWISKA,NAZWA) values ('3','Psycholog');
REM INSERTING into SYSTEM.PRZEDMIOTY
SET DEFINE OFF;
Insert into SYSTEM.PRZEDMIOTY (ID_PRZEDMIOTU,NAZWA_PRZEDMIOTU) values ('1','Hipoterapia');
Insert into SYSTEM.PRZEDMIOTY (ID_PRZEDMIOTU,NAZWA_PRZEDMIOTU) values ('2','Dogoterapia');
Insert into SYSTEM.PRZEDMIOTY (ID_PRZEDMIOTU,NAZWA_PRZEDMIOTU) values ('3','Muzykoterapia');
Insert into SYSTEM.PRZEDMIOTY (ID_PRZEDMIOTU,NAZWA_PRZEDMIOTU) values ('4','Logopedia');
Insert into SYSTEM.PRZEDMIOTY (ID_PRZEDMIOTU,NAZWA_PRZEDMIOTU) values ('5','Sensoplastyka');
REM INSERTING into SYSTEM.NAUCZYCIELE
SET DEFINE OFF;
Insert into SYSTEM.NAUCZYCIELE (ID_NAUCZYCIELA,IMIE,NAZWISKO,ID_STANOWISKA,ID_PRZEDMIOTU) values ('1','Maciej','Turutko','1','1');
Insert into SYSTEM.NAUCZYCIELE (ID_NAUCZYCIELA,IMIE,NAZWISKO,ID_STANOWISKA,ID_PRZEDMIOTU) values ('2','Teresa','Kowadelko','2','2');
Insert into SYSTEM.NAUCZYCIELE (ID_NAUCZYCIELA,IMIE,NAZWISKO,ID_STANOWISKA,ID_PRZEDMIOTU) values ('3','Marian','Opanika','1','3');
REM INSERTING into SYSTEM.LISTA_OBCENOSCI
SET DEFINE OFF;
REM INSERTING into SYSTEM.GRUPY
SET DEFINE OFF;
Insert into SYSTEM.GRUPY (ID_GRUPY,DATA_ZALOZENIA,NAZWA_GRUPY,ID_PRACOWNIKA) values ('1',to_date('17/09/01','RR/MM/DD'),'A','1');
Insert into SYSTEM.GRUPY (ID_GRUPY,DATA_ZALOZENIA,NAZWA_GRUPY,ID_PRACOWNIKA) values ('2',to_date('17/09/01','RR/MM/DD'),'B','2');
Insert into SYSTEM.GRUPY (ID_GRUPY,DATA_ZALOZENIA,NAZWA_GRUPY,ID_PRACOWNIKA) values ('3',to_date('17/09/01','RR/MM/DD'),'C','3');
--------------------------------------------------------
--  DDL for Index UCZNIOWIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UCZNIOWIE_PK" ON "SYSTEM"."UCZNIOWIE" ("ID_UCZNIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STANOWISKA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."STANOWISKA_PK" ON "SYSTEM"."STANOWISKA" ("ID_STANOWISKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRZEDMIOTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PRZEDMIOTY_PK" ON "SYSTEM"."PRZEDMIOTY" ("ID_PRZEDMIOTU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NAUCZYCIELE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."NAUCZYCIELE_PK" ON "SYSTEM"."NAUCZYCIELE" ("ID_NAUCZYCIELA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LISTA_OBCENOSCI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."LISTA_OBCENOSCI_PK" ON "SYSTEM"."LISTA_OBCENOSCI" ("ID_REKORDU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GRUPY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GRUPY_PK" ON "SYSTEM"."GRUPY" ("ID_GRUPY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger UCZNIOWIE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."UCZNIOWIE_TRG" 
BEFORE INSERT ON UCZNIOWIE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."UCZNIOWIE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UCZNIOWIE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."UCZNIOWIE_TRG1" 
BEFORE INSERT ON UCZNIOWIE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_UCZNIA IS NULL THEN
      SELECT UCZNIOWIE_SEQ1.NEXTVAL INTO :NEW.ID_UCZNIA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."UCZNIOWIE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STANOWISKA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."STANOWISKA_TRG" 
BEFORE INSERT ON STANOWISKA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_STANOWISKA IS NULL THEN
      SELECT STANOWISKA_SEQ.NEXTVAL INTO :NEW.ID_STANOWISKA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."STANOWISKA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRZEDMIOTY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."PRZEDMIOTY_TRG" 
BEFORE INSERT ON PRZEDMIOTY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PRZEDMIOTU IS NULL THEN
      SELECT PRZEDMIOTY_SEQ.NEXTVAL INTO :NEW.ID_PRZEDMIOTU FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PRZEDMIOTY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NAUCZYCIELE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."NAUCZYCIELE_TRG" 
BEFORE INSERT ON NAUCZYCIELE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_NAUCZYCIELA IS NULL THEN
      SELECT NAUCZYCIELE_SEQ.NEXTVAL INTO :NEW.ID_NAUCZYCIELA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."NAUCZYCIELE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LISTA_OBCENOSCI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."LISTA_OBCENOSCI_TRG" 
BEFORE INSERT ON LISTA_OBCENOSCI 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_REKORDU IS NULL THEN
      SELECT LISTA_OBCENOSCI_SEQ.NEXTVAL INTO :NEW.ID_REKORDU FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."LISTA_OBCENOSCI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger GRUPY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."GRUPY_TRG" 
BEFORE INSERT ON GRUPY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_GRUPY IS NULL THEN
      SELECT GRUPY_SEQ.NEXTVAL INTO :NEW.ID_GRUPY FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."GRUPY_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table UCZNIOWIE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."UCZNIOWIE" ADD CONSTRAINT "UCZNIOWIE_PK" PRIMARY KEY ("ID_UCZNIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."UCZNIOWIE" MODIFY ("ID_UCZNIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STANOWISKA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STANOWISKA" ADD CONSTRAINT "STANOWISKA_PK" PRIMARY KEY ("ID_STANOWISKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."STANOWISKA" MODIFY ("ID_STANOWISKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRZEDMIOTY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PRZEDMIOTY" ADD CONSTRAINT "PRZEDMIOTY_PK" PRIMARY KEY ("ID_PRZEDMIOTU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PRZEDMIOTY" MODIFY ("ID_PRZEDMIOTU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NAUCZYCIELE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NAUCZYCIELE" ADD CONSTRAINT "NAUCZYCIELE_PK" PRIMARY KEY ("ID_NAUCZYCIELA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."NAUCZYCIELE" MODIFY ("ID_NAUCZYCIELA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LISTA_OBCENOSCI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LISTA_OBCENOSCI" ADD CONSTRAINT "LISTA_OBCENOSCI_PK" PRIMARY KEY ("ID_REKORDU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."LISTA_OBCENOSCI" MODIFY ("ID_REKORDU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRUPY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GRUPY" ADD CONSTRAINT "GRUPY_PK" PRIMARY KEY ("ID_GRUPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GRUPY" MODIFY ("ID_GRUPY" NOT NULL ENABLE);
